#!/usr/bin/env python3
"""Emit workshop-grade MSP logs without committing binary blobs.

This helper reconstructs the trimmed MSP captures that ship with Drone Chorus so
students can demo the MSP→MIDI bridge offline. The log payloads live as base64
inside this script to keep the repo text-only while still letting folks
regenerate the `.mspbin` files with one command.
"""
from __future__ import annotations

import argparse
import base64
import pathlib
from typing import Dict

EMBEDDED_LOGS: Dict[str, str] = {
    # Calm hover + RC trims
    "example_log_01.mspbin": """
        JE08BmwAABMAAAB5JE08EGncBQQG0wTrBdwF3AXcBdwFmyRNPAduKgAAXwAAABwkTTwGbAMAFAAF
        AHgkTTwQad8FBAbVBPEF3AXcBdwF3AWEJE08B24qAABeAAAAHSRNPAZsBgAVAAoAcyRNPBBp4wUF
        BtgE9wXcBdwF3AXcBbIkTTwHbioAAF4AAAAdJE08BmwJABUADwB5JE08EGnmBQYG2gT8BdwF3AXc
        BdwFvSRNPAduKgAAXgAAAB0kTTwGbAwAFgAUAGQkTTwQaeoFBgbdBAEG3AXcBdwF3AVIJE08B24q
        AABeAAAAHSRNPAZsDwAXABkAayRNPBBp7QUHBt8EBgbcBdwF3AXcBUskTTwHbioAAF4AAAAdJE08
        BmwSABgAHgB+JE08EGnxBQcG4gQLBtwF3AXcBdwFZyRNPAduKgAAXgAAAB0kTTwGbBUAGQAjAEUk
        TTwQafQFBwbkBA8G3AXcBdwF3AVgJE08B24qAABeAAAAHSRNPAZsGAAZACgAQyRNPBBp9wUIBuYE
        FAbcBdwF3AXcBXUkTTwHbioAAF4AAAAdJE08BmwaABoALQBHJE08EGn6BQgG6QQYBtwF3AXcBdwF
        eyRNPAduKgAAXgAAAB0kTTwGbB0AGgAyAF8kTTwQaf0FCAbrBBsG3AXcBdwF3AV9JE08B24qAABe
        AAAAHSRNPAZsHwAbADcAWSRNPBBpAAYIBu0EHwbcBdwF3AXcBYEkTTwHbioAAF4AAAAdJE08Bmwi
        ABsAPABvJE08EGkDBggG8AQiBtwF3AXcBdwFoiRNPAduKgAAXgAAAB0kTTwGbCQAHABBABMkTTwQ
        aQYGCAbyBCQG3AXcBdwF3AWjJE08B24qAABdAAAAHiRNPAZsJgAcAEYAFiRNPBBpCAYIBvQEJgbc
        BdwF3AXcBakkTTwHbioAAF0AAAAeJE08BmwoAB0ASwAUJE08EGkKBggG9gQoBtwF3AXcBdwFpyRN
        PAduKgAAXQAAAB4kTTwGbCoAHQBQAA0kTTwQaQwGCAb4BCoG3AXcBdwF3AWtJE08B24qAABdAAAA
        HiRNPAZsKwAdAFUACSRNPBBpDgYIBvoEKwbcBdwF3AXcBawkTTwHbioAAF0AAAAeJE08BmwtAB0A
        WgAAJE08EGkQBggG/AQrBtwF3AXcBdwFtCRNPAduKgAAXQAAAB4kTTwGbC4AHQBfAAYkTTwQaRIG
        CAb+BCsG3AXcBdwF3AW0JE08B24qAABdAAAAHiRNPAZsLwAdAGQAPCRNPBBpEwYHBgAFKwbcBdwF
        3AXcBUUkTTwHbioAAF0AAAAeJE08BmwwAB0AaQAuJE08EGkVBgcGAgUrBtwF3AXcBdwFQSRNPAdu
        KgAAXQAAAB4kTTwGbDEAHQBuACgkTTwQaRYGBwYEBSoG3AXcBdwF3AVFJE08B24qAABdAAAAHiRN
        PAZsMQAdAHMANSRNPBBpFgYGBgYFKAbcBdwF3AXcBUQkTTwHbioAAF0AAAAeJE08BmwxAB0AeAA+
        JE08EGkXBgYGCAUmBtwF3AXcBdwFRSRNPAduKgAAXQAAAB4kTTwGbDIAHQB9ADgkTTwQaRcGBQYK
        BSQG3AXcBdwF3AVGJE08B24qAABdAAAAHiRNPAZsMQAdAIIAxCRNPBBpFwYEBgsFIQbcBdwF3AXc
        BUMkTTwHbioAAF0AAAAeJE08BmwxAB0AhwDBJE08EGkXBgQGDQUeBtwF3AXcBdwFeiRNPAduKgAA
        XAAAAB8kTTwGbDEAHACMAMskTTwQaRcGAwYPBRsG3AXcBdwF3AV6JE08B24qAABcAAAAHyRNPAZs
        MAAcAJEA1yRNPBBpFwYCBhAFFwbcBdwF3AXcBWgkTTwHbioAAFwAAAAfJE08BmwvABwAlgDPJE08
        EGkWBgEGEgUTBtwF3AXcBdwFbCRNPAduKgAAXAAAAB8kTTwGbC4AGwCbAMQkTTwQaRUGAQYTBQ8G
        3AXcBdwF3AVyJE08B24qAABcAAAAHyRNPAZsLQAbAKAA/CRNPBBpFAYABhUFCwbcBdwF3AXcBXAk
        TTwHbioAAFwAAAAfJE08BmwrABoApQD+JE08EGkTBv8FFgUGBtwF3AXcBdwFhSRNPAduKgAAXAAA
        AB8kTTwGbCoAGgCqAPAkTTwQaREG/gUXBQEG3AXcBdwF3AWAJE08B24qAABcAAAAHyRNPAZsKAAZ
        AK8A9CRNPBBpEAb9BRkF/AXcBdwF3AXcBXIkTTwHbioAAFwAAAAfJE08BmwmABgAtADgJE08EGkO
        BvwFGgX2BdwF3AXcBdwFZCRNPAduKgAAXAAAAB8kTTwGbCQAGAC5AO8kTTwQaQwG+wUbBfEF3AXc
        BdwF3AVnJE08B24qAABcAAAAHyRNPAZsIgAXAL4A4SRNPBBpCQb5BRwF6wXcBdwF3AXcBX0kTTwH
        bioAAFwAAAAfJE08BmwfABYAwwCgJE08EGkHBvgFHQXlBdwF3AXcBdwFfSRNPAduKgAAXAAAAB8k
        TTwGbB0AFQDIAKokTTwQaQUG9wUeBeAF3AXcBdwF3AV2JE08B24qAABcAAAAHyRNPAZsGgAUAM0A
        qSRNPBBpAgb2BR8F2gXcBdwF3AXcBUskTTwHbioAAFsAAAAYJE08BmwYABMA0gCzJE08EGn/BfUF
        IAXUBdwF3AXcBdwFhyRNPAduKgAAWwAAABgkTTwGbBUAEgDXALokTTwQafwF8wUhBc4F3AXcBdwF
        3AWZJE08B24qAABbAAAAGCRNPAZsEgASANwAtiRNPBBp+QXyBSIFyQXcBdwF3AXcBZkkTTwHbioA
        AFsAAAAYJE08BmwPABEA4QCVJE08EGn2BfEFIwXDBdwF3AXcBdwFniRNPAduKgAAWwAAABgkTTwG
        bAwAEADmAJAkTTwQafMF7wUjBb4F3AXcBdwF3AX4JE08B24qAABbAAAAGCRNPAZsCQAOAOsAhiRN
        PBBp7wXuBSQFuAXcBdwF3AXcBeQkTTwHbioAAFsAAAAYJE08BmwGAA0A8ACRJE08EGnsBewFJQWz
        BdwF3AXcBdwF7yRNPAduKgAAWwAAABgkTTwGbAMADAD1AJAkTTwQaegF6wUlBa4F3AXcBdwF3AXx
        JE08B24qAABbAAAAGCRNPAZsAAALAPoAmyRNPBBp5QXpBSYFqgXcBdwF3AXcBfkkTTwHbioAAFsA
        AAAYJE08Bmz9/woA/wCdJE08EGnhBegFJgWlBdwF3AXcBdwF8yRNPAduKQAAWwAAABskTTwGbPr/
        CQAEAWMkTTwQad4F5gUnBaEF3AXcBdwF3AXHJE08B24pAABbAAAAGyRNPAZs9/8IAAkBYiRNPBBp
        2gXlBScFnQXcBdwF3AXcBfwkTTwHbikAAFsAAAAbJE08Bmz0/wcADgFpJE08EGnXBeMFJwWaBdwF
        3AXcBdwF8CRNPAduKQAAWwAAABskTTwGbPH/BQATAXMkTTwQadMF4gUnBZcF3AXcBdwF3AX4JE08
        B24pAABbAAAAGyRNPAZs7v8EABgBZiRNPBBp0AXgBScFlAXcBdwF3AXcBfokTTwHbikAAFsAAAAb
        JE08Bmzr/wMAHQFhJE08EGnMBd8FJwWSBdwF3AXcBdwF3yRNPAduKQAAWwAAABskTTwGbOj/AgAi
        AVwkTTwQackF3QUnBZAF3AXcBdwF3AXaJE08B24pAABbAAAAGyRNPAZs5v8AACcBVSRNPBBpxQXc
        BScFjgXcBdwF3AXcBckkTTwHbikAAFsAAAAbJE08Bmzj/wAALAFbJE08EGnCBdoFJwWNBdwF3AXc
        BdwFyyRNPAduKQAAWgAAABokTTwGbOH///8xAUQkTTwQab8F2QUnBYwF3AXcBdwF3AW0JE08B24p
        AABaAAAAGiRNPAZs3v/+/zYBfSRNPBBpvAXXBScFjAXcBdwF3AXcBbkkTTwHbikAAFoAAAAaJE08
        Bmzc//3/OwFxJE08EGm5BdUFJwWMBdwF3AXcBdwFviRNPAduKQAAWgAAABokTTwGbNr/+/9AAQok
        TTwQabYF1AUmBYwF3AXcBdwF3AWxJE08B24pAABaAAAAGiRNPAZs2P/6/0UBDCRNPBBpswXSBSYF
        jQXcBdwF3AXcBbMkTTwHbikAAFoAAAAaJE08BmzW//n/SgEOJE08EGmxBdEFJgWOBdwF3AXcBdwF
        sSRNPAduKQAAWgAAABokTTwGbNX/+P9PAQkkTTwQaa4FzwUlBZAF3AXcBdwF3AWtJE08B24pAABa
        AAAAGiRNPAZs0//3/1QBGyRNPBBprAXOBSQFkgXcBdwF3AXcBa0kTTwHbikAAFoAAAAaJE08BmzS
        //X/WQEVJE08EGmqBcwFJAWUBdwF3AXcBdwFryRNPAduKQAAWgAAABokTTwGbNH/9P9eARAkTTwQ
        aagFywUjBZcF3AXcBdwF3AWuJE08B24pAABaAAAAGiRNPAZs0P/z/2MBKyRNPBBppgXJBSIFmgXc
        BdwF3AXcBa4kTTwHbikAAFoAAAAaJE08BmzP//L/aAE+JE08EGmlBcgFIgWeBdwF3AXcBdwFqCRN
        PAduKQAAWgAAABokTTwGbM//8f9tATgkTTwQaaMFxwUhBaIF3AXcBdwF3AWeJE08B24pAABaAAAA
        GiRNPAZsz//w/3IBJiRNPBBpogXFBSAFpgXcBdwF3AXcBZgkTTwHbikAAFoAAAAaJE08BmzO/+//
        dwE9JE08EGmhBcQFHwWqBdwF3AXcBdwFqSRNPAduKQAAWgAAABokTTwGbM//7v98ATYkTTwQaaAF
        wwUeBa8F3AXcBdwF3AWrJE08B24pAABaAAAAGiRNPAZsz//t/4EByCRNPBBpoAXBBR0FtAXcBdwF
        3AXcBbEkTTwHbikAAFoAAAAaJE08BmzP/+z/hgHOJE08EGmgBcAFHAW5BdwF3AXcBdwFvCRNPAdu
        KQAAWgAAABokTTwGbND/6/+LAdskTTwQaaAFvwUbBb4F3AXcBdwF3AXDJE08B24pAABaAAAAGiRN
        PAZs0f/q/5ABwCRNPBBpoAW+BRkFxAXcBdwF3AXcBbokTTwHbikAAFoAAAAaJE08BmzS/+r/lQHG
        JE08EGmgBb0FGAXJBdwF3AXcBdwFtSRNPAduKQAAWgAAABokTTwGbNP/6f+aAcskTTwQaaAFuwUX
        Bc8F3AXcBdwF3AW6JE08B24pAABaAAAAGiRNPAZs1f/o/58BySRNPBBpoQW6BRYF1QXcBdwF3AXc
        BaEkTTwHbikAAFoAAAAaJE08BmzW/+f/pAH+JE08EGmiBbkFFAXaBdwF3AXcBdwFrCRNPAduKQAA
        WgAAABokTTwGbNj/5/+pAf0kTTwQaaMFuAUTBeAF3AXcBdwF3AWRJE08B24pAABaAAAAGiRNPAZs
        2v/m/64B+SRNPBBppQW3BREF5gXcBdwF3AXcBZwkTTwHbikAAFoAAAAaJE08Bmzc/w==
    """,
    # Stick wiggles for CC movement
    "example_log_02.mspbin": """
        5v+zAeIkTTwQaaYFtwUQBewF3AXcBdwF3AWUJE08B24pAABaAAAAGiRNPAZs3v/l/7gB6CRNPBBp
        qAW2BQ4F8QXcBdwF3AXcBZgkTTwHbikAAFoAAAAaJE08Bmzh/+X/vQHSJE08EGmqBbUFDAX3BdwF
        3AXcBdwFnSRNPAduKQAAWgAAABokTTwGbOP/5P/CAa4kTTwQaawFtAULBfwF3AXcBdwF3AWWJE08
        B24pAABaAAAAGiRNPAZs5v/k/8cBriRNPBBprgWzBQkFAQbcBdwF3AXcBW8kTTwHbikAAFoAAAAa
        JE08Bmzo/+P/zAGsJE08EGmxBbMFBwUGBtwF3AXcBdwFeSRNPAduKQAAWgAAABokTTwGbOv/4//R
        AbIkTTwQabMFsgUFBQsG3AXcBdwF3AV1JE08B24pAABaAAAAGiRNPAZs7v/j/9YBsCRNPBBptgWx
        BQMFEAbcBdwF3AXcBW4kTTwHbikAAFoAAAAaJE08Bmzx/+P/2wGiJE08EGm5BbEFAgUUBtwF3AXc
        BdwFZCRNPAduKQAAWgAAABokTTwGbPT/4//gAZwkTTwQabwFsAUABRgG3AXcBdwF3AVuJE08B24p
        AABaAAAAGiRNPAZs9//j/+UBmiRNPBBpvwWwBf4EGwbcBdwF3AXcBZEkTTwHbikAAFoAAAAaJE08
        Bmz6/+P/6gGYJE08EGnCBbAF/AQfBtwF3AXcBdwF6iRNPAduKQAAWgAAABokTTwGbP3/4//vAZok
        TTwQacYFrwX5BCIG3AXcBdwF3AXJJE08B24pAABaAAAAGiRNPAZsAADj//QBgyRNPBBpyQWvBfcE
        JAbcBdwF3AXcBc4kTTwHbikAAFoAAAAaJE08BmwDAOP/+QGNJE08EGnMBa8F9QQmBtwF3AXcBdwF
        yyRNPAduKQAAWgAAABokTTwGbAYA4//+AY8kTTwQadAFrwXzBCgG3AXcBdwF3AXfJE08B24pAABa
        AAAAGiRNPAZsCQDj/wMCfiRNPBBp0wWvBfEEKgbcBdwF3AXcBdwkTTwHbikAAFoAAAAaJE08BmwM
        AOP/CAJwJE08EGnXBa8F7wQrBtwF3AXcBdwFxyRNPAduKQAAWgAAABokTTwGbA8A5P8NAnEkTTwQ
        adsFrwXsBCsG3AXcBdwF3AXIJE08B24pAABaAAAAGiRNPAZsEgDk/xICcyRNPBBp3gWvBeoEKwbc
        BdwF3AXcBcskTTwHbikAAFoAAAAaJE08BmwVAOT/FwJxJE08EGniBa8F6AQrBtwF3AXcBdwF9SRN
        PAduKQAAWgAAABokTTwGbBgA5f8cAnYkTTwQaeUFrwXlBCsG3AXcBdwF3AX/JE08B24pAABaAAAA
        GiRNPAZsGgDl/yECSSRNPBBp6QWvBeMEKgbcBdwF3AXcBfQkTTwHbikAAFoAAAAaJE08BmwdAOb/
        JgJKJE08EGnsBa8F4QQoBtwF3AXcBdwF8SRNPAduKQAAWgAAABokTTwGbB8A5v8rAkUkTTwQafAF
        sAXeBCYG3AXcBdwF3AXDJE08B24pAABaAAAAGiRNPAZsIgDn/zACYiRNPBBp8wWwBdwEJAbcBdwF
        3AXcBcAkTTwHbikAAFoAAAAaJE08BmwkAOj/NQJuJE08EGn2BbAF2QQhBtwF3AXcBdwFxSRNPAdu
        KQAAWgAAABokTTwGbCYA6P86AmMkTTwQafkFsQXXBB4G3AXcBdwF3AX6JE08B24pAABaAAAAGiRN
        PAZsKADp/z8CaSRNPBBp/AWxBdQEGwbcBdwF3AXcBfkkTTwHbikAAFoAAAAaJE08BmwqAOr/RAIT
        JE08EGn/BbIF0gQXBtwF3AXcBdwF8yRNPAduKQAAWgAAABokTTwGbCsA6/9JAh4kTTwQaQIGswXP
        BBMG3AXcBdwF3AUVJE08B24pAABaAAAAGiRNPAZsLQDs/04CGCRNPBBpBQazBc0EDwbcBdwF3AXc
        BQwkTTwHbikAAFoAAAAaJE08BmwuAO3/UwIHJE08EGkHBrQFygQKBtwF3AXcBdwFCyRNPAduKQAA
        WgAAABokTTwGbC8A7v9YAg4kTTwQaQoGtQXIBAYG3AXcBdwF3AUJJE08B24pAABaAAAAGiRNPAZs
        MADv/10CFSRNPBBpDAa2BcUEAQbcBdwF3AXcBQYkTTwHbikAAFoAAAAaJE08BmwxAPD/YgI0JE08
        EGkOBrYFwgT7BdwF3AXcBdwF+iRNPAduKQAAWgAAABokTTwGbDEA8f9nAjAkTTwQaRAGtwXABPYF
        3AXcBdwF3AXqJE08B24pAABaAAAAGiRNPAZsMQDy/2wCOCRNPBBpEQa4Bb0E8AXcBdwF3AXcBZ8k
        TTwHbikAAFoAAAAaJE08BmwyAPP/cQInJE08EGkTBrkFuwTrBdwF3AXcBdwFgSRNPAduKQAAWgAA
        ABokTTwGbDEA9P92AiQkTTwQaRQGugW4BOUF3AXcBdwF3AWIJE08B24pAABaAAAAGiRNPAZsMQD1
        /3sCKCRNPBBpFQa7BbUE3wXcBdwF3AXcBb8kTTwHbikAAFoAAAAaJE08BmwxAPb/gALQJE08EGkW
        Br0FswTaBdwF3AXcBdwFuSRNPAduKQAAWgAAABokTTwGbDAA9/+FAtUkTTwQaRcGvgWwBNQF3AXc
        BdwF3AW2JE08B24pAABaAAAAGiRNPAZsLwD4/4oCyiRNPBBpFwa/Ba0EzgXcBdwF3AXcBbAkTTwH
        bikAAFoAAAAaJE08BmwuAPr/jwLMJE08EGkXBsAFqwTIBdwF3AXcBdwFzyRNPAduKQAAWgAAABok
        TTwGbC0A+/+UAtUkTTwQaRcGwQWoBMMF3AXcBdwF3AXGJE08B24pAABaAAAAGiRNPAZsKwD8/5kC
        2SRNPBBpFwbDBaYEvQXcBdwF3AXcBbQkTTwHbikAAFoAAAAaJE08BmwqAP3/ngLeJE08EGkXBsQF
        owS4BdwF3AXcBdwFsyRNPAduKQAAWgAAABokTTwGbCgA/v+jAuIkTTwQaRYGxQWgBLMF3AXcBdwF
        3AW7JE08B24pAABaAAAAGiRNPAZsJgAAAKgC5iRNPBBpFQbHBZ4ErgXcBdwF3AXcBZkkTTwHbikA
        AFoAAAAaJE08BmwkAAAArQLhJE08EGkUBsgFmwSqBdwF3AXcBdwFliRNPAduKQAAWgAAABokTTwG
        bCIAAQCyAvkkTTwQaRMGyQWYBKUF3AXcBdwF3AWcJE08B24pAABaAAAAGiRNPAZsHwACALcCwiRN
        PBBpEgbLBZYEoQXcBdwF3AXcBZUkTTwHbikAAFoAAAAaJE08BmwdAAQAvALNJE08EGkQBswFkwSd
        BdwF3AXcBdwFqSRNPAduKQAAWgAAABokTTwGbBoABQDBArYkTTwQaQ4GzgWRBJoF3AXcBdwF3AWw
        JE08B24pAABbAAAAGyRNPAZsGAAGAMYCsCRNPBBpDAbPBY4ElwXcBdwF3AXcBaEkTTwHbikAAFsA
        AAAbJE08BmwVAAcAywKxJE08EGkKBtEFjASUBdwF3AXcBdwFuCRNPAduKQAAWwAAABskTTwGbBIA
        CADQAqIkTTwQaQgG0gWJBJIF3AXcBdwF3AW6JE08B24pAABbAAAAGyRNPAZsDwAJANUCuyRNPBBp
        BQbUBYcEkAXcBdwF3AXcBb0kTTwHbikAAFsAAAAbJE08BmwMAAsA2gK1JE08EGkDBtUFhASOBdwF
        3AXcBdwFpyRNPAduKQAAWwAAABskTTwGbAkADADfArIkTTwQaQAG1wWCBI0F3AXcBdwF3AWjJE08
        B24pAABbAAAAGyRNPAZsBgANAOQChyRNPBBp/QXYBX8EjAXcBdwF3AXcBa4kTTwHbikAAFsAAAAb
        JE08BmwDAA4A6QKMJE08EGn6BdoFfQSMBdwF3AXcBdwFqSRNPAduKQAAWwAAABskTTwGbAAADwDu
        AokkTTwQafcF3AV7BIwF3AXcBdwF3AWkJE08B24oAABbAAAAGiRNPAZs/f8QAPMCiSRNPBBp9AXd
        BXgEjAXcBdwF3AXcBaUkTTwHbigAAFsAAAAaJE08Bmz6/xEA+AKEJE08EGnwBd8FdgSNBdwF3AXc
        BdwFrCRNPAduKAAAWwAAABokTTwGbPf/EgD9Ao8kTTwQae0F4AV0BI4F3AXcBdwF3AWPJE08B24o
        AABbAAAAGiRNPAZs9P8TAAIDcyRNPBBp6QXiBXEEkAXcBdwF3AXcBZIkTTwHbigAAFsAAAAaJE08
        Bmzx/xQABwN0JE08EGnmBeMFbwSSBdwF3AXcBdwFgCRNPAduKAAAWwAAABokTTwGbO7/FQAMA2Ek
        TTwQaeIF5QVtBJQF3AXcBdwF3AWGJE08B24oAABbAAAAGiRNPAZs6/8WABEDeiRNPBBp3wXmBWsE
        lwXcBdwF3AXcBb0kTTwHbigAAFsAAAAaJE08Bmzo/xYAFgN+JE08EGnbBegFaQSaBdwF3AXcBdwF
        uCRNPAduKAAAWwAAABokTTwGbOb/FwAbA3wkTTwQadgF6QVmBJ4F3AXcBdwF3AWxJE08B24oAABb
        AAAAGiRNPAZs4/8YACADTSRNPBBp1AXrBWQEogXcBdwF3AXcBYEkTTwHbigAAFwAAAAdJE08Bmzh
        /xkAJQNLJE08EGnQBewFYgSmBdwF3AXcBdwFgCRNPAduKAAAXAAAAB0kTTwGbN7/GQAqA3skTTwQ
        ac0F7gVgBKoF3AXcBdwF3AWRJE08B24oAABcAAAAHSRNPAZs3P8aAC8DfyRNPBBpyQXvBV4ErwXc
        BdwF3AXcBa8kTTwHbigAAFwAAAAdJE08Bmza/xoANANiJE08EGnGBfAFXAS0BdwF3AXcBdwFpiRN
        PAduKAAAXAAAAB0kTTwGbNj/GwA5A2wkTTwQacMF8gVbBLkF3AXcBdwF3AWrJE08B24oAABcAAAA
        HSRNPAZs1v8bAD4DZSRNPBBpwAXzBVkEvgXcBdwF3AXcBawkTTwHbigAAFwAAAAdJE08BmzV/xwA
        QwMcJE08EGm8BfQFVwTEBdwF3AXcBdwFoyRNPAduKAAAXAAAAB0kTTwGbNP/HABIAxEkTTwQabkF
        9gVVBMkF3AXcBdwF3AWrJE08B24oAABcAAAAHSRNPAZs0v8dAE0DFCRNPBBptwX3BVMEzwXcBdwF
        3AXcBaQkTTwHbigAAFwAAAAdJE08BmzR/x0AUgMIJE08EGm0BfgFUgTVBdwF3AXcBdwFsyRNPAdu
        KAAAXAAAAB0kTTwGbND/HQBXAwwkTTwQabEF+QVQBNsF3AXcBdwF3AW7JE08B24oAABcAAAAHSRN
        PAZsz/8dAFwDGCRNPBBprwX7BU8E4AXcBdwF3AXcBYMkTTwHbigAAFwAAAAdJE08BmzP/x0AYQMl
        JE08EGmsBfwFTQTmBdwF3AXcBdwFgyRNPAduKAAAXAAAAB0kTTwGbM//HQBmAyIkTQ==
    """,
    # Brownout / voltage sag recovery
    "example_log_03.mspbin": """
        PBBpqgX9BUwE7AXcBdwF3AXcBY8kTTwHbigAAF0AAAAcJE08BmzO/x0AawMuJE08EGmoBf4FSgTx
        BdwF3AXcBdwFlSRNPAduKAAAXQAAABwkTTwGbM//HQBwAzQkTTwQaacF/wVJBPcF3AXcBdwF3AWe
        JE08B24oAABdAAAAHCRNPAZsz/8dAHUDMSRNPBBppQUABkcE/AXcBdwF3AXcBWUkTTwHbigAAF0A
        AAAcJE08BmzP/x0AegM+JE08EGmkBQEGRgQCBtwF3AXcBdwFmSRNPAduKAAAXQAAABwkTTwGbND/
        HQB/AyQkTTwQaaIFAQZFBAcG3AXcBdwF3AWZJE08B24oAABdAAAAHCRNPAZs0f8dAIQD3iRNPBBp
        oQUCBkQECwbcBdwF3AXcBZQkTTwHbigAAF0AAAAcJE08BmzS/x0AiQPQJE08EGmhBQMGQwQQBtwF
        3AXcBdwFiSRNPAduKAAAXQAAABwkTTwGbNP/HACOA9ckTTwQaaAFBAZBBBQG3AXcBdwF3AWJJE08
        B24oAABdAAAAHCRNPAZs1f8cAJMDzCRNPBBpoAUEBkAEGAbcBdwF3AXcBYQkTTwHbigAAF0AAAAc
        JE08BmzW/xwAmAPEJE08EGmgBQUGPwQcBtwF3AXcBdwF/iRNPAduKAAAXQAAABwkTTwGbNj/GwCd
        A8gkTTwQaaAFBgY/BB8G3AXcBdwF3AX+JE08B24oAABdAAAAHCRNPAZs2v8bAKID9SRNPBBpoAUG
        Bj4EIgbcBdwF3AXcBcIkTTwHbigAAF0AAAAcJE08Bmzc/xoApwP3JE08EGmgBQcGPQQkBtwF3AXc
        BdwFxiRNPAduKAAAXQAAABwkTTwGbN7/GQCsA/0kTTwQaaEFBwY8BCcG3AXcBdwF3AXFJE08B24o
        AABeAAAAHyRNPAZs4f8ZALED3yRNPBBpogUHBjsEKAbcBdwF3AXcBc4kTTwHbigAAF4AAAAfJE08
        Bmzj/xgAtgPbJE08EGmjBQgGOwQqBtwF3AXcBdwFwiRNPAduKAAAXgAAAB8kTTwGbOb/FwC7A9wk
        TTwQaaQFCAY6BCsG3AXcBdwF3AXFJE08B24oAABeAAAAHyRNPAZs6P8XAMADqSRNPBBppgUIBjoE
        KwbcBdwF3AXcBcckTTwHbigAAF4AAAAfJE08Bmzr/xYAxQOuJE08EGmoBQgGOQQrBtwF3AXcBdwF
        yiRNPAduKAAAXgAAAB8kTTwGbO7/FQDKA6ckTTwQaakFCAY5BCsG3AXcBdwF3AXLJE08B24oAABe
        AAAAHyRNPAZs8f8UAM8DvCRNPBBprAUIBjgEKwbcBdwF3AXcBc8kTTwHbigAAF4AAAAfJE08Bmz0
        /xMA1AOlJE08EGmuBQgGOAQpBtwF3AXcBdwFzyRNPAduKAAAXgAAAB8kTTwGbPf/EgDZA6okTTwQ
        abAFCAY4BCgG3AXcBdwF3AXQJE08B24oAABeAAAAHyRNPAZs+v8RAN4DoyRNPBBpswUIBjgEJgbc
        BdwF3AXcBd0kTTwHbigAAF4AAAAfJE08Bmz9/xAA4wOYJE08EGm1BQgGOAQkBtwF3AXcBdwF2SRN
        PAduKAAAXgAAAB8kTTwGbAAADwDoA44kTTwQabgFCAY4BCEG3AXcBdwF3AXRJE08B24oAABfAAAA
        HiRNPAZsAwAOAO0DiSRNPBBpuwUIBjgEHgbcBdwF3AXcBe0kTTwHbigAAF8AAAAeJE08BmwGAA0A
        8gOQJE08EGm+BQcGOAQbBtwF3AXcBdwF4iRNPAduKAAAXwAAAB4kTTwGbAkADAD3A5skTTwQacEF
        BwY4BBcG3AXcBdwF3AWRJE08B24oAABfAAAAHiRNPAZsDAALAPwDkiRNPBBpxQUHBjgEEwbcBdwF
        3AXcBZEkTTwHbigAAF8AAAAeJE08BmwPAAoAAQRqJE08EGnIBQYGOAQPBtwF3AXcBdwFgSRNPAdu
        KAAAXwAAAB4kTTwGbBIACQAGBHMkTTwQacsFBgY4BAoG3AXcBdwF3AWHJE08B24oAABfAAAAHiRN
        PAZsFQAIAAsEeCRNPBBpzwUFBjkEBQbcBdwF3AXcBY4kTTwHbigAAF8AAAAeJE08BmwYAAYAEARg
        JE08EGnSBQQGOQQABtwF3AXcBdwFlyRNPAduKAAAXwAAAB4kTTwGbBoABQAVBGQkTTwQadYFBAY6
        BPsF3AXcBdwF3AVoJE08B24oAABfAAAAHiRNPAZsHQAEABoEbSRNPBBp2gUDBjoE9gXcBdwF3AXc
        BW4kTTwHbigAAF8AAAAeJE08BmwfAAMAHwRtJE08EGndBQIGOwTwBdwF3AXcBdwFbyRNPAduKAAA
        XwAAAB4kTTwGbCIAAQAkBGkkTTwQaeEFAQY7BOsF3AXcBdwF3AVLJE08B24oAABfAAAAHiRNPAZs
        JAAAACkEYyRNPBBp5AUABjwE5QXcBdwF3AXcBUYkTTwHbigAAGAAAAAhJE08BmwmAAAALgRmJE08
        EGnoBQAGPQTfBdwF3AXcBdwFcSRNPAduKAAAYAAAACEkTTwGbCgA//8zBHUkTTwQaesF/wU9BNkF
        3AXcBdwF3AWIJE08B24oAABgAAAAISRNPAZsKgD+/zgEfSRNPBBp7wX+BT4E1AXcBdwF3AXcBYMk
        TTwHbigAAGAAAAAhJE08BmwrAPz/PQR7JE08EGnyBf0FPwTOBdwF3AXcBdwFhiRNPAduKAAAYAAA
        ACEkTTwGbC0A+/9CBAUkTTwQafUF/AVABMgF3AXcBdwF3AX5JE08B24oAABgAAAAISRNPAZsLgD6
        /0cEAiRNPBBp+QX6BUEEwwXcBdwF3AXcBfkkTTwHbigAAGAAAAAhJE08BmwvAPn/TAQLJE08EGn8
        BfkFQgS9BdwF3AXcBdwFgiRNPAduKAAAYAAAACEkTTwGbDAA+P9RBAgkTTwQaf8F+AVDBLgF3AXc
        BdwF3AWEJE08B24oAABgAAAAISRNPAZsMQD2/1YEACRNPBBpAQb3BUQEswXcBdwF3AXcBXokTTwH
        bigAAGAAAAAhJE08BmwxAPX/WwQOJE08EGkEBvYFRgSuBdwF3AXcBdwFYSRNPAduKAAAYAAAACEk
        TTwGbDEA9P9gBDQkTTwQaQcG9AVHBKkF3AXcBdwF3AVmJE08B24oAABgAAAAISRNPAZsMgDz/2UE
        NSRNPBBpCQbzBUgEpQXcBdwF3AXcBWwkTTwHbigAAGAAAAAhJE08BmwxAPL/agQ4JE08EGkLBvIF
        SgShBdwF3AXcBdwFaSRNPAduKAAAYAAAACEkTTwGbDEA8f9vBD4kTTwQaQ0G8AVLBJ0F3AXcBdwF
        3AVQJE08B24oAABhAAAAICRNPAZsMQDw/3QEJCRNPBBpDwbvBU0EmgXcBdwF3AXcBUwkTTwHbigA
        AGEAAAAgJE08BmwwAO//eQQ3JE08EGkRBu0FTgSXBdwF3AXcBdwFXiRNPAduKAAAYQAAACAkTTwG
        bC8A7v9+BC4kTTwQaRMG7AVQBJQF3AXcBdwF3AVAJE08B24oAABhAAAAICRNPAZsLgDt/4ME0SRN
        PBBpFAbrBVEEkQXcBdwF3AXcBUQkTTwHbigAAGEAAAAgJE08BmwtAOz/iATYJE08EGkVBukFUwSP
        BdwF3AXcBdwFWyRNPAduKAAAYQAAACAkTTwGbCsA6/+NBNwkTTwQaRYG6AVVBI4F3AXcBdwF3AVe
        JE08B24oAABhAAAAICRNPAZsKgDq/5IEwyRNPBBpFwbmBVYEjQXcBdwF3AXcBVEkTTwHbigAAGEA
        AAAgJE08BmwoAOr/lwTEJE08EGkXBuUFWASMBdwF3AXcBdwFXSRNPAduKAAAYQAAACAkTTwGbCYA
        6f+cBMIkTTwQaRcG4wVaBIwF3AXcBdwF3AVZJE08B24oAABhAAAAICRNPAZsJADo/6EE/CRNPBBp
        FwbiBVwEjAXcBdwF3AXcBV4kTTwHbigAAGEAAAAgJE08BmwiAOf/pgTyJE08EGkXBuAFXgSMBdwF
        3AXcBdwFXiRNPAduKAAAYQAAACAkTTwGbB8A5/+rBMIkTTwQaRcG3gVgBI0F3AXcBdwF3AVfJE08
        B24oAABhAAAAICRNPAZsHQDm/7AE2iRNPBBpFgbdBWIEjgXcBdwF3AXcBVwkTTwHbigAAGEAAAAg
        JE08BmwaAOb/tQTYJE08EGkWBtsFZASQBdwF3AXcBdwFQiRNPAduKAAAYgAAACMkTTwGbBgA5f+6
        BNYkTTwQaRUG2gVmBJIF3AXcBdwF3AVAJE08B24oAABiAAAAIyRNPAZsFQDl/78E3iRNPBBpEwbY
        BWgElQXcBdwF3AXcBU0kTTwHbigAAGIAAAAjJE08BmwSAOT/xASjJE08EGkSBtcFagSXBdwF3AXc
        BdwFQyRNPAduKAAAYgAAACMkTTwGbA8A5P/JBLMkTTwQaREG1QVsBJsF3AXcBdwF3AVIJE08B24o
        AABiAAAAIyRNPAZsDADj/84EsCRNPBBpDwbUBW4EngXcBdwF3AXcBVAkTTwHbigAAGIAAAAjJE08
        BmwJAOP/0wSoJE08EGkNBtIFcQSiBdwF3AXcBdwFdyRNPAduKAAAYgAAACMkTTwGbAYA4//YBKwk
        TTwQaQsG0QVzBKYF3AXcBdwF3AV0JE08B24oAABiAAAAIyRNPAZsAwDj/90ErCRNPBBpCAbPBXUE
        qwXcBdwF3AXcBWIkTTwHbigAAGIAAAAjJE08BmwAAOP/4gSQJE08EGkGBs4FeASvBdwF3AXcBdwF
        ZCRNPAduKAAAYgAAACMkTTwGbP3/4//nBJckTTwQaQMGzAV6BLQF3AXcBdwF3AV6JE08B24nAABi
        AAAALCRNPAZs+v/j/+wEmyRNPBBpAQbLBXwEuQXcBdwF3AXcBXQkTTwHbicAAGIAAAAsJE08Bmz3
        /+P/8QSLJE08EGn+BckFfwS/BdwF3AXcBdwFjyRNPAduJwAAYgAAACwkTTwGbPT/4//2BI8kTTwQ
        afsFyAWBBMQF3AXcBdwF3AUOJE08B24nAABiAAAALCRNPAZs8f/j//sEhyRNPBBp+AXGBYMEygXc
        BdwF3AXcBQ8kTTwHbicAAGIAAAAsJE08Bmzu/+P/AAViJE08EGn0BcUFhgTPBdwF3AXcBdwFACRN
        PAduJwAAYgAAACwkTTwGbOv/4/8FBWIkTTwQafEFxAWIBNUF3AXcBdwF3AUQJE08B24nAABiAAAA
        LCRNPAZs6P/j/woFbiRNPBBp7gXCBYsE2wXcBdwF3AXcBQQkTTwHbicAAGIAAAAsJE08Bmzm/+T/
        DwViJE08EGnqBcEFjQThBdwF3AXcBdwFPyRNPAduJwAAYgAAACwkTTwGbOP/5P8UBXwkTTwQaecF
        wAWQBOYF3AXcBdwF3AUpJE08B24nAABjAAAALSRNPAZs4f/k/xkFcyRNPBBp4wW/BZME7AXcBdwF
        3AXcBVskTTwHbicAAGMAAAAtJE08Bmze/+X/HgVKJE08EGngBb4FlQTyBdwF3AXcBdwFQSRNPAdu
        JwAAYwAAAC0kTTwGbNz/5f8jBXUkTTwQadwFvAWYBPcF3AXcBdwF3AV3JE08B24nAABjAAAALSRN
        PAZs2v/m/ygFeyRNPBBp2AW7BZoE/QXcBdwF3AXcBXwkTTwHbicAAGMAAAAtJE08BmzY/+f/LQV9
        JE08EGnVBboFnQQCBtwF3AXcBdwFiyRNPAduJwAAYwAAAC0kTTwGbNb/5/8yBWwkTTwQadEFuQWg
        BAcG3AXcBdwF3AW0JE08B24nAABjAAAALSRNPAZs1f/o/zcFZSRNPBBpzgW4BaIECwbcBdwF3AXc
        BaQkTTwHbicAAGMAAAAtJE08BmzT/+n/PAVpJE08EGnKBbcFpQQQBtwF3AXcBdwFsyRNPAduJwAA
        YwAAAC0kTTwGbNL/6f9BBRUkTTwQaccFtgWnBBQG3AXcBdwF3AW5JE08B24nAABjAAAALSRNPAZs
        0f/q/0YFEiRNPBBpxAW1BaoEGAbcBdwF3AXcBbgkTTwHbicAAGMAAAAtJE08BmzQ/+v/SwUfJE08
        EGnABbUFrQQcBtwF3AXcBdwFvyRNPAduJwAAYwAAAC0kTTwGbM//7P9QBRwkTTwQab0FtAWvBB8G
        3AXcBdwF3AXCJE08B24nAABjAAAALSRNPAZsz//t/1UFGCRNPBBpugWzBbIEIgbcBdwF3AXcBeIk
        TTwHbicAAGMAAAAtJE08BmzP/+7/WgUUJE08EGm3BbMFtQQkBtwF3AXcBdwF7iRNPAduJwAAYwAA
        AC0kTTwGbM7/7/9fBREkTTwQabUFsgW3BCcG3AXcBdwF3AXsJE08B24nAABjAAAALSRNPAZsz//w
        /2QFNCRNPBBpsgWxBboEKAbcBdwF3AXcBeokTTwHbicAAGMAAAAtJE08BmzP//H/aQU4JE08EGmv
        BbEFvAQqBtwF3AXcBdwF8yRNPAduJwAAYwAAAC0kTTwGbM//8v9uBTwkTTwQaa0FsAW/BCsG3AXc
        BdwF3AXyJE08B24nAABjAAAALSRNPAZs0P/z/3MFPyRNPBBpqwWwBcIEKwbcBdwF3AXcBYkkTTwH
        bicAAGMAAAAtJE08BmzR//T/eAUyJE08EGmpBbAFxAQrBtwF3AXcBdwFjSRNPAduJwAAYwAAAC0k
        TTwGbNL/9f99BTUkTTwQaacFrwXHBCsG3AXcBdwF3AWfJE08B24nAABjAAAALSRNPAZs0//2/4IF
        yCRNPBBppQWvBckEKwbcBdwF3AXcBZMkTTwHbicAAGMAAAAtJE08BmzV//f/hwXKJE08EGmkBa8F
        zAQpBtwF3AXcBdwFlSRNPAduJwAAYwAAAC0kTTwGbNb/+f+MBcwkTTwQaaMFrwXPBCgG3AXcBdwF
        3AWQJE08B24nAABjAAAALSRNPAZs2P/6/5EF3CRNPBBpogWvBdEEJgbcBdwF3AXcBYEkTTwHbicA
        AGMAAAAtJE08Bmza//v/lgXYJE08EGmhBa8F1AQkBtwF3AXcBdwFhSRNPAduJwAAYwAAAC0kTTwG
        bNz//P+bBdQkTTwQaaAFrwXWBCEG3AXcBdwF3AWDJE08B24nAABjAAAALSRNPAZs3v/9/6AF7CRN
        PBBpoAWvBdkEHgbcBdwF3AXcBbMkTTwHbicAAGMAAAAtJE08Bmzh////pQXUJE08EGmgBa8F2wQb
        BtwF3AXcBdwFtCRNPAduJwAAYwAAAC0kTTwGbOP/AACqBdkkTTwQaaAFrwXeBBcG3AXcBdwF3AW9
        JE08B24nAABjAAAALSRNPAZs5v8AAK8F2SRNPBBpoAWvBeAEEwbcBdwF3AXcBYckTTwHbicAAGMA
        AAAtJE08Bmzo/wEAtAXNJE08EGmgBa8F4gQPBtwF3AXcBdwFmSRNPAduJwAAYwAAAC0kTTwGbOv/
        AgC5BcAkTTwQaaEFsAXlBAoG3AXcBdwF3AWFJE08B24nAABjAAAALSRNPAZs7v8EAL4FxCRNPBBp
        ogWwBecEBQbcBdwF3AXcBYskTTwHbicAAGMAAAAtJE08Bmzx/wUAwwWnJE08EGmjBbAF6QQABtwF
        3AXcBdwFgSRNPAduJwAAYwAAAC0kTTwGbPT/BgDIBaokTTwQaaQFsQXsBPsF3AXcBdwF3AV6JE08
        B24nAABjAAAALSRNPAZs9/8HAM0FrSRNPBBppQWyBe4E9QXcBdwF3AXcBXQkTTwHbicAAGMAAAAt
        JE08Bmz6/wgA0gWwJE08EGmnBbIF8ATwBdwF3AXcBdwFbSRNPAduJwAAYwAAAC0kTTwGbP3/CgDX
        BbAkTTwQaakFswXyBOoF3AXcBdwF3AV6JE08B24nAABjAAAALQ==
    """,
}


def decode_log(payload: str) -> bytes:
    """Strip whitespace and base64-decode a payload."""
    squished = ''.join(payload.split())
    return base64.b64decode(squished)


def write_logs(output_dir: pathlib.Path, force: bool = False) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for name, payload in EMBEDDED_LOGS.items():
        target = output_dir / name
        if target.exists() and not force:
            print(f"[skip] {target} exists; use --force to overwrite")
            continue
        target.write_bytes(decode_log(payload))
        print(f"[write] {target}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Recreate the sample MSP logs used by examples/replay_log.py. "
            "Run this once after cloning so the data/ folder matches the README."
        )
    )
    parser.add_argument(
        "--output-dir",
        default="data",
        type=pathlib.Path,
        help="Where to drop the decoded .mspbin files (default: data/)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files instead of skipping them",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    write_logs(args.output_dir, force=args.force)


if __name__ == "__main__":
    main()
